### ISSUE TITLE
First deploy

### ISSUE THREAD

**Issue by johndacost** [HE-Arc/ValEvasion#1]
[Read section **Apache** and **mod_wsgi**](https://docs.djangoproject.com/fr/2.0/topics/install/)

**Comment by greut** [comment]
apache + mod_wsgi ?? Essayez nginx + uwsgi

**Comment by Gandus10** [comment]
[nginx and uwsgi for django](http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html)
