### ISSUE TITLE
Email system

### ISSUE THREAD

**Issue by johndacost** [HE-Arc/ValEvasion#11]

**Comment by johndacost** [comment]
@Gandus10 @grunenwald  Le problème c'est que tu as utilisé le port **465 (SSL)**, mais google propose un autre port qui est le **587 (TLS/STARTTLS)**. On peut utilisé le port **465** à condition d'appeler `smtplib.SMTP_SSL()`  alors que django utilise `smtplib.SMTP()`.
![image](https://user-images.githubusercontent.com/3956368/36788567-b4f7166c-1c8e-11e8-9bcc-f679e4155270.png) source : https://support.google.com/mail/answer/7104828?hl=en&visit_id=1-636554191310010012-2751018229&rd=3

Solution : https://code.djangoproject.com/ticket/9575

**Comment by grunenwald** [comment]
Pour le smtp de l'école : https://intranet.he-arc.ch/si/Pages/FAQ.aspx 
Déplier Mail / Généralités / IMAP
En résumé le serveur SMTP est utilisable sans auth à condition d'être à l'intérieur de l'école (ou en dmz, ça devrait jouer aussi depuis srvz-webapp. On compte sur vous pour l'utiliser de façon raisonnable.
