### ISSUE TITLE
Make a schema of the database

### ISSUE THREAD

**Issue by johndacost** [HE-Arc/ValEvasion#3]
Describe the different models that will be used in the database

**Comment by greut** [comment]
Django works the other way around, you may stick to the high level Entity-Relationship (_Entités-Associations_) diagram.

**Comment by johndacost** [comment]
**First shot**
![entity-relationship-valevasion](https://user-images.githubusercontent.com/3956368/36150399-deadbc44-10c3-11e8-86b7-265cd71e80a1.PNG)

**Comment by greut** [comment]
then: https://djangopackages.org/
